name: android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

  assemble:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Assemble project
        run: ./gradlew assembleDebug

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Test
        run: ./gradlew test

  lint:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Lint
        run: ./gradlew lint

      - name: Ktlint
        run: ./gradlew ktlintCheck

  debug:
    runs-on: ubuntu-latest

    needs: assemble

    steps:
      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
