name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build project
        run: ./gradlew build

  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Ktlint
        run: ./gradlew ktlintCheck

  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
