name: android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3
      - uses: gradle/actions/wrapper-validation@v3

  assemble:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ./gradlew assembleDebug
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ./gradlew test
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ./gradlew lint
      - run: ./gradlew ktlintCheck
  debug:
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
