name: Upload APK

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  debug_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
