name: release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew assemble
      - run: ./gradlew app:bundleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/apk/release/app-release.aab
