name: release
on:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew assembleRelease
      - run: ./gradlew app:bundleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            app/build/outputs/apk/release/*
            app/build/outputs/bundle/release/*
